[package]
name = "shindex-rust-tracer-challenge"
version = "0.1.0"
authors = ["alcyz <tobias_schindler@hotmail.de>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
png = "0.15.0"
